### ISSUE TITLE
Browsersync doesn't reload on SCSS changes

### ISSUE THREAD

**Issue by adamkolson** [tomaszbujnowicz/frontie#1] opened 2018-09-14 18:34 UTC
With the default tasks, everything is compiled and neat for the StyleSheets directory. But Browsersync doesn't work, maybe intentionally as it can take a few milliseconds to compile? I've been poking around and can't seem to get it to work. Probably obvious.

**Comment by tomaszbujnowicz** [comment] 2018-09-16 10:38
Thanks for the note. It works just fine here so could you please let me know steps to reproduce the issue? Do you use the latest version of files from git?

**Comment by adamkolson** [comment] 2018-09-17 03:22
I cloned the latest from Git. Here's what I get on a fresh version below. Perhaps I should clarify: is it on purpose that only files in `template` (but not `components` or `layouts`) and `sass` don't reload? I just edited some files: `index.twig` causes Browsersync to reload as does `main.js`. `default.twig` and `_variables.scss`. I tried editing `gulpfile.js` but couldn't figure out why they weren't caused Browsersync to say "[Browsersync] Reloading Browsers...". Probably something obvious if it's intentional and I can figure it out.

[Browsersync] Serving files from: ./dist
[Browsersync] Watching files...
[23:03:43] Starting 'twig'...
[23:03:43] Finished 'twig' after 35 ms
[Browsersync] Reloading Browsers...
[23:04:02] Starting 'twig'...
[23:04:02] Finished 'twig' after 31 ms
[23:04:24] Starting 'css'...
[Browsersync] 2 files changed (main.css.map, main.css)
[23:04:25] Finished 'css' after 800 ms
[23:17:00] Starting 'js:main'...
[Browsersync] 2 files changed (main.min.js.map, main.min.js)
[23:17:00] Finished 'js:main' after 195 ms
[Browsersync] Reloading Browsers... (buffered 2 events)

**Comment by tomaszbujnowicz** [comment] 2018-09-17 09:46
It's because the CSS is injected into the page and there is no message in the terminal so you should not care about these messages. Just to clarify, when you change the CSS e.g. in main.scss, the site doesn't refresh and you don't see new styles, is that correct? Or you see them but it's only about "Reloading Browsers..." message in the terminal that you are concerned?

**Comment by tomaszbujnowicz** [comment] 2018-09-28 07:27
Closing, please re-open if this is still an issue.

**Closed as completed by tomaszbujnowicz** 2018-09-28 07:27 UTC
